### PR TITLE
Use MOAR ES6.

### PR DESCRIPTION
**Pull request by rwjblue**
* Kill `var`
* Use `() => {}` instead of `function() {}.bind(this)`
* Use destructuring to grab `this.inputPaths[0]`

### CODE REVIEW

**Comment by trentmwillis** [comment]
Seems good, but before merging I want to clear up one thing: are we preferring `let` over `const`? I tend to prefer `const`, but I'm not dogmatic about it

**Comment by rwjblue** [comment]
In general, we have been using `let` by default for Ember itself (and even have a rule to prevent usage of `const` outside of module scope).  I basically follow the "liberal let" philosophy from http://madhatted.com/2016/1/25/let-it-be.

That being said, I do not _really_ care to argue about it.  I'm happy to change these `let`'s to `const`'s if you feel strongly about it...

**Comment by trentmwillis** [comment]
As I said, I'm not dogmatic about it and don't care to argue about it either (god knows how many hours have been wasted over it), I just want to make sure we're explicit about the decision. If `let` is the general convention for Ember core, then we should likely follow that here as well.

**Comment by trentmwillis** [comment]
Let it be known, we will prefer `let`.

**Pull request merged**
